### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ztowne13** [weaondara/BungeePerms#111]
Idk why this doesn't work....
I get this error on startup.
the conflicting plugins is BungeeAdminTools and i need to know how I can fix it. Thanks. Code:

[SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@48802d16, id=4, owner=fr.Alphart.BAT.BAT@66a4156c, task=fr.Alphart.BAT.BAT$3@1e7a9a19, delay=0, period=0, running=true) encountered an exception

java.lang.ClassCastException: net.alpenblock.bungeeperms.platform.bungee.BungeePlugin cannot be cast to net.alpenblock.bungeeperms.BungeePerms

    at fr.Alphart.BAT.Modules.Core.Core.load(Core.java:155)

    at fr.Alphart.BAT.Modules.ModulesManager.loadModules(ModulesManager.java:81)

    at fr.Alphart.BAT.BAT$2.done(BAT.java:111)

    at fr.Alphart.BAT.BAT$2.done(BAT.java:103)

    at fr.Alphart.BAT.BAT$3.run(BAT.java:165)

    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)

    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

    at java.lang.Thread.run(Thread.java:744)

**Comment by weaondara** [comment]
ok ... another plugin that does not support bp 3.0
i'll write to the author to fix that problem ...
meanwhile please downgrade bungeeperms to 2.6
