### ISSUE TITLE
Error with featherboard

### ISSUE THREAD

**Issue by xion87** [weaondara/BungeePerms#123]
After a while, player that logout from my hub server get this error:
[15:09:35 INFO]: Saimon lost connection: Disconnected
[15:09:35 WARN]: java.util.ConcurrentModificationException
[15:09:35 WARN]:        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
[15:09:35 WARN]:        at java.util.ArrayList$Itr.next(ArrayList.java:851)
[15:09:35 WARN]:        at net.alpenblock.bungeeperms.bukkit.PermissionsManager.getUser(PermissionsManager.java:313)
[15:09:35 WARN]:        at net.alpenblock.bungeeperms.bukkit.PermissionsManager.hasPermOrConsoleOnServerInWorld(PermissionsManager.java:560)
[15:09:35 WARN]:        at net.alpenblock.bungeeperms.bukkit.Permissible.hasPermission(Permissible.java:67)
[15:09:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102)
[15:09:35 WARN]:        at be.maximvdw.featherboard.a.d(Unknown Source)
[15:09:35 WARN]:        at be.maximvdw.featherboard.c.a(Unknown Source)
[15:09:35 WARN]:        at be.maximvdw.featherboard.c.run(Unknown Source)
[15:09:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
[15:09:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:09:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:09:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:09:35 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by phil568622** [comment]
Did you check if the errors still appear without BungeePerms, maybe test using PEX?

As far as I know, Featherboard is very buggy...

**Comment by xion87** [comment]
Featherboard author say:
"thats not an error in featherboard but your bungeeperms plugin "

**Comment by weaondara** [comment]
this indeed is a bp error ...
https://github.com/weaondara/BungeePerms/issues/83

**Comment by weaondara** [comment]
fixed in https://github.com/weaondara/BungeePerms/commit/171473af3bc9760dedd4ab94385133bc7aae1928
