### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by dylanweb2** [weaondara/BungeePerms#136]
I've migrated my permissions over to SQL using my Bungee server and now want to link my servers to it however the command /bp backend mysql2 isn't a command anymore? so you have to migrate which formats the existing database.

**Comment by weaondara** [comment]
the new command is /bp migrate backend mysql2

**Comment by dylanweb2** [comment]
But when I do that on my bungee server it works but then when I do it on my spigot servers it overwrites the existing database with the template permissions..

**Comment by weaondara** [comment]
conversion should only be done once
check the configs on the server if useUUID is set to true after the conversion has finished
if not set to true do so and do a bp reload

**Comment by dylanweb2** [comment]
Bungee says it's using mysql2 but my spigot servers are saying they are using YAML even though it's set to mysql2 in config

**Comment by dylanweb2** [comment]
[SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4fce655d, id=4, owner=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin@7e6f74c, task=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin$1$1@2c4e63b3, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
	at net.alpenblock.bungeeperms.io.MySQL2BackEnd.saveUser(MySQL2BackEnd.java:501)
	at net.alpenblock.bungeeperms.io.migrate.Migrate2MySQL2.migrate(Migrate2MySQL2.java:36)
	at net.alpenblock.bungeeperms.PermissionsManager.migrateBackEnd(PermissionsManager.java:1382)
	at net.alpenblock.bungeeperms.CommandHandler.handleMigrateBackend(CommandHandler.java:2044)
	at net.alpenblock.bungeeperms.CommandHandler.handleMigrate(CommandHandler.java:1991)
	at net.alpenblock.bungeeperms.CommandHandler.onCommand(CommandHandler.java:86)
	at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onCommand(BungeePlugin.java:82)
	at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin$1$1.run(BungeePlugin.java:99)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by dylanweb2** [comment]
Nevermind just spend an hour going through thousands of users and found the error.
