### ISSUE TITLE
Error im zusammenhang mit BungeeTabListPlus

### ISSUE THREAD

**Issue by Rustypredator** [weaondara/BungeePerms#171]
Hi,
wie viele hier bereits geschrieben haben, ist dieses Plugin wirklich einzigartig, und funktioniert eigentlich auch ohne Probleme, bis auf folgendes:
Sobald jemand auf den Server joint, wird diese Errormeldung ca. jede halbe Sekunde pro Spieler in der Bungeecord Konsole "gespammt".
Sobald alle Spieler runter sind, hören die Errormeldungen umgehend auf.
```java
16:07:28 [SCHWERWIEGEND] Okt 22, 2015 4:07:28 PM net.md_5.bungee.event.EventBus post
WARNUNG: Error dispatching event PermissionCheckEvent(sender=Rustypredator, permission=bungeetablistplus.seevanished, hasPermission=false) to listener net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener@a3d9978
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:432)
    at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInWorld(PermissionsChecker.java:334)
    at net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener.onPermissionCheck(BungeeEventListener.java:119)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)
    at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:466)
    at codecrafter47.bungeetablistplus.managers.PermissionManager.hasPermission(PermissionManager.java:315)
    at codecrafter47.bungeetablistplus.managers.PlayerManagerImpl.<init>(PlayerManagerImpl.java:47)
    at codecrafter47.bungeetablistplus.BungeeTabListPlus.constructPlayerManager(BungeeTabListPlus.java:455)
    at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:94)
    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:63)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)



```
So wie es für mich aussieht, liegt irgendein Fehler im zusammenhang mit @CodeCrafter47 's TabList vor.
Könnte dies ein Konfigurationsproblem sein? in der Tablist habe ich keine Spieler in die hidden Liste eingetragen.

Ich benutze die aktuellsten Versionen von 
- Bungeecord
- Spigot
- BungeeTabListPlus
- BungeePortals
- BungeePerms

Auf Java 1.8

**Comment by CodeCrafter47** [comment]
uuidplayerdb: MySQL

sollte das Problem beheben.

**Comment by Rustypredator** [comment]
Super, das hat funktioniert.
bzw, ich habe einfach die UUIDs ausgeschaltet. Danke!

**Comment by brainscript** [comment]
@Rustypredator UUIDs ausschalten ist auch keine tolle Lösung. Denn sollten Spieler ihren Namen ändern, verlieren diese ihren Rang.

**Je nach Größe deines Server ist das entweder egal oder ein ziemlich Risiko:**
Moderator *Fr0xlix564* ändert seinen Namen zu *Fr0xlixPvP*. Falls sich nun ein Spieler *Fr0xlix564* hat dieser Moderatoren-Rang was er vielleicht für bööööse Machenschaften missbrauchen könnte.
