### ISSUE TITLE
Groups not available via Vault

### ISSUE THREAD

**Issue by zedwick** [weaondara/BungeePerms#176]
Using the plugin Ontime, I get the following in the console. Ontime tries to retrieve a player's groups for ranking them up based on playtime.

[10:09:43 WARN]: [OnTime] Task #608840 for OnTime v4.1.2 generated an exceptionjava.lang.UnsupportedOperationException: SuperPerms no group permissions.        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.playerAddGroup(Permission_SuperPerms.java:81) ~[?:?]        at net.milkbowl.vault.permission.Permission.playerAddGroup(Permission.java:592) ~[?:?]        at me.edge209.OnTime.PermissionsHandler.action(PermissionsHandler.java:96) ~[?:?]        at me.edge209.OnTime.PermissionsHandler._addOrRemove(PermissionsHandler.java:45) ~[?:?]        at me.edge209.OnTime.PermissionsHandler.addOrRemove(PermissionsHandler.java:35) ~[?:?]        at me.edge209.OnTime.Rewards.Rewards.issue(Rewards.java:2016) ~[?:?]        at me.edge209.OnTime.Rewards.Rewards$issueReward.run(Rewards.java:191) ~[?:?]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Zz.jar:git-Spigot-f928e7a-994b2aa]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Zz.jar:git-Spigot-f928e7a-994b2aa]        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [Zz.jar:git-Spigot-f928e7a-994b2aa]        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [Zz.jar:git-Spigot-f928e7a-994b2aa]        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Zz.jar:git-Spigot-f928e7a-994b2aa]        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Zz.jar:git-Spigot-f928e7a-994b2aa]

Using BungeePerms 3 beta.

**Comment by CodeCrafter47** [comment]
Vault support is broken in the version that can be downloaded from the spigot website. This has already been fixed. To get a fixed version you can either download the latest dev-build or compile the plugin yourself.

**Comment by zedwick** [comment]
Ooh, great! Thanks.

**Comment by zedwick** [comment]
Confirmed, all working in the latest dev build. Thanks again!
