### ISSUE TITLE
Bungeecord hangs on startup

### ISSUE THREAD

**Issue by Rustypredator** [weaondara/BungeePerms#196]
```
16:11:10 [INFORMATION] Using OpenSSL based native cipher.
16:11:10 [INFORMATION] Using native code compressor
16:11:10 [INFORMATION] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b6e26e0":1093
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Loaded plugin FreeBungeeChat version 2.3 by CodeCrafter47
16:11:10 [INFORMATION] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"b6e26e0":1093 by SpigotMC
16:11:10 [INFORMATION] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"b6e26e0":1093 by SpigotMC
16:11:10 [INFORMATION] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"b6e26e0":1093 by SpigotMC
16:11:10 [INFORMATION] [BungeePerms] extracting lang/EN-gb.yml
16:11:10 [INFORMATION] [BungeePerms] extracted lang/EN-gb.yml
```
EN
Bungeecord hangs itself upon startup while "extracting" what seems to be languagepacks...

DE
Bungeecord hängt sich beim starten auf, wärend etwas das aussieht wie sprachpakete entpackt werden

**Comment by Rustypredator** [comment]
okay update:
```
16:11:10 [INFORMATION] Using OpenSSL based native cipher.
16:11:10 [INFORMATION] Using native code compressor
16:11:10 [INFORMATION] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b6e26e0":1093
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
16:11:10 [INFORMATION] Loaded plugin FreeBungeeChat version 2.3 by CodeCrafter47
16:11:10 [INFORMATION] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"b6e26e0":1093 by SpigotMC
16:11:10 [INFORMATION] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"b6e26e0":1093 by SpigotMC
16:11:10 [INFORMATION] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"b6e26e0":1093 by SpigotMC
16:11:10 [INFORMATION] [BungeePerms] extracting lang/EN-gb.yml
16:11:10 [INFORMATION] [BungeePerms] extracted lang/EN-gb.yml
16:17:36 [SCHWERWIEGEND] com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
16:17:36 [SCHWERWIEGEND]        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
16:17:36 [SCHWERWIEGEND]        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
16:17:36 [SCHWERWIEGEND]        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
16:17:36 [SCHWERWIEGEND]        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.Util.getInstance(Util.java:360)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2144)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
16:17:36 [SCHWERWIEGEND]        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
16:17:36 [SCHWERWIEGEND]        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
16:17:36 [SCHWERWIEGEND]        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
16:17:36 [SCHWERWIEGEND]        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
16:17:36 [SCHWERWIEGEND]        at java.sql.DriverManager.getConnection(DriverManager.java:664)
16:17:36 [SCHWERWIEGEND]        at java.sql.DriverManager.getConnection(DriverManager.java:247)
16:17:36 [SCHWERWIEGEND]        at net.alpenblock.bungeeperms.Mysql.connect(Mysql.java:40)
16:17:36 [SCHWERWIEGEND]        at net.alpenblock.bungeeperms.io.MySQL2BackEnd.<init>(MySQL2BackEnd.java:44)
16:17:36 [SCHWERWIEGEND]        at net.alpenblock.bungeeperms.PermissionsManager.loadConfig(PermissionsManager.java:85)
16:17:36 [SCHWERWIEGEND]        at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:62)
16:17:36 [SCHWERWIEGEND]        at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)
16:17:36 [SCHWERWIEGEND]        at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
16:17:36 [SCHWERWIEGEND]        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
16:17:36 [SCHWERWIEGEND]        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
16:17:36 [SCHWERWIEGEND]        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:247)
16:17:36 [SCHWERWIEGEND]        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
16:17:36 [SCHWERWIEGEND]        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
16:17:36 [SCHWERWIEGEND] Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
16:17:36 [SCHWERWIEGEND]        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
16:17:36 [SCHWERWIEGEND]        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
16:17:36 [SCHWERWIEGEND]        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
16:17:36 [SCHWERWIEGEND]        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
16:17:36 [SCHWERWIEGEND]        ... 23 more
16:17:36 [SCHWERWIEGEND] Caused by: java.net.ConnectException: Die Wartezeit für die Verbindung ist abgelaufen
16:17:36 [SCHWERWIEGEND]        at java.net.PlainSocketImpl.socketConnect(Native Method)
16:17:36 [SCHWERWIEGEND]        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
16:17:36 [SCHWERWIEGEND]        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
16:17:36 [SCHWERWIEGEND]        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
16:17:36 [SCHWERWIEGEND]        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
16:17:36 [SCHWERWIEGEND]        at java.net.Socket.connect(Socket.java:589)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
16:17:36 [SCHWERWIEGEND]        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
16:17:36 [SCHWERWIEGEND]        ... 25 more
```
Der fehler scheint bei mir zu liegen :) sorry

**Comment by Rustypredator** [comment]
So... der fehler ist immernoch vorhanden, obwohl man auf die Datenbank von extern zugreifen kann... habe es gerade von meinem heimrechner versucht...
kann es sein, dass es einen fehler in der config gibt?
```
useUUIDs: false
useregexperms: false
grouppermission: true
backendtype: MySQL2
uuidplayerdb: MySQL
tablePrefix: bungeeperms_
uuidfetcher:
  cooldown: 3000
saveAllUsers: true
deleteUsersOnCleanup: false
notify:
  promote: false
  demote: false
tabcomplete: false
locale: en-GB
networktype: Global
networkservers: []
debug:
  path: /home/florian/bungeecord/plugins/BungeePerms/debug.log
  showexceptions: true
  showlogs: false
terminate:
  prefix:
    reset: true
    space: true
  suffix:
    reset: true
    space: true
cleanup:
  interval: 1800
  threshold: 600
bungeeperms:
  general:
    mysqlhost: ***
    mysqlport: '3306'
    mysqldb: ***
    mysqluser: ***
    mysqlpw: ***
async-commands: true
```

**Comment by weaondara** [comment]
fehler liegt eindeutig bei der datenbank verbindung

**Comment by weaondara** [comment]
firewall, port oder ähnliches ... connect failt komplett

**Comment by Rustypredator** [comment]
warum kann ich denn dann von zuhause aus zugreifen?
port ist in der firewall offen, und ich kann ja wie gesagt drauf zugreifen

**Comment by weaondara** [comment]
`The driver has not received any packets from the server.`
steht da
vlt mysql user remote endpoint permissions?

**Comment by weaondara** [comment]
mal `mysql -host=<yourhost> ...` probieren

**Comment by Rustypredator** [comment]
seltsame kiste...
von außen geht es, aber nicht wenn ich vom bungeecord server vebinde, mit der internen ip hats jetzt geklappt ^^
