### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by cathat1234** [weaondara/BungeePerms#230]
21:59:11 [SCHWERWIEGEND] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@137c20c1, id=9, owner=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin@47c44bd4, task=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin$1$1@578aca63, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:432)
    at net.alpenblock.bungeeperms.PermissionsChecker.hasPerm(PermissionsChecker.java:196)
    at net.alpenblock.bungeeperms.PermissionsChecker.hasOrConsole(PermissionsChecker.java:391)
    at net.alpenblock.bungeeperms.CommandHandler.handleHelp(CommandHandler.java:98)
    at net.alpenblock.bungeeperms.CommandHandler.onCommand(CommandHandler.java:42)
    at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onCommand(BungeePlugin.java:81)
    at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin$1$1.run(BungeePlugin.java:98)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Seit einiger Zeit bekomme ich diese Fehlermeldung wenn ich als Spieler ein Command eingebe das mit BungeePerms zutun hat. Woran könnte es liegen?

**Comment by weaondara** [comment]
welche version? nur bi bp befehlen? stimmt useuuid überall überein?

**Comment by cathat1234** [comment]
die aktuellste version. ja, Stimmt überall.

**Comment by weaondara** [comment]
dev build oder von spigotmc

**Comment by weaondara** [comment]
sieht nach spigotmc version aus ... nicht nach dev build

**Comment by cathat1234** [comment]
12:35:18 [WARNUNG] Error enabling plugin BungeePerms
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.BPConfig.validate(BPConfig.java:95)
    at net.alpenblock.bungeeperms.BPConfig.load(BPConfig.java:88)
    at net.alpenblock.bungeeperms.platform.bungee.BungeeConfig.load(BungeeConfig.java:25)
    at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:53)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:247)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
12:35:18 [WARNUNG] Exception encountered when loading plugin: BungeePerms
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onEnable(BungeePlugin.java:72)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Bei der Dev Build Version kommt dieser fehler. Bin mir nicht mehr sicher welche es war.

**Comment by weaondara** [comment]
sieht so aus als ob du useuuids auf true und uuidplayerdb auf none gesetzt hast ...
