### ISSUE TITLE
Bungeecord permissions

### ISSUE THREAD

**Issue by TheSDTM** [weaondara/BungeePerms#239]
Hello. I set permission for group "admin" to '*', but I don't have a lot of permissions. Then I tried to add permission "bungeeperms.*", I reloaded server, but nothing happened - I can't execute any bungeeperms commands in game. When I write group permission list, it shows that there are all permissions, which I added. I have the same problem with BungeeCordMemoryUsage, SkinsRestorer, etc. I think, it only happens when plugin is for bungeecord.

**Comment by phil568622** [comment]
Please try enabling Regex Permissions in your config.

**Comment by TheSDTM** [comment]
It doesn't help me. I still get the same problem.

**Comment by TheSDTM** [comment]
<img width="325" alt="2016-03-04 17 24 08" src="https://cloud.githubusercontent.com/assets/13622053/13525842/04d6c77e-e22e-11e5-9712-51d84ed15842.png">

**Comment by TheSDTM** [comment]
<img width="275" alt="2016-03-04 17 24 21" src="https://cloud.githubusercontent.com/assets/13622053/13525846/0ce68cc4-e22e-11e5-8623-2eac99c218aa.png">
it is my config. I change regex permissions to true in server and bungeecord

**Comment by phil568622** [comment]
Could you give yourself the permission *, restart both servers and see if it works?

**Comment by phil568622** [comment]
Oh, and please enable UseUUIDs in both configs. What Backend are you using?

**Comment by TheSDTM** [comment]
I use Mysql2

**Comment by TheSDTM** [comment]
UseUUIDs - it was enabled only in server config, not in bungeecord, I enabled it in bungeecord too, but the same problem

**Comment by TheSDTM** [comment]
I set my own permission to *, now I can use /bungeeperms reload and another, but I can't use it in group.
And I had this error after giving permission
olExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
12:50:37 [INFO] [vaneagps] -> UpstreamBridge has disconnected
12:50:37 [SEVERE] Mar 04, 2016 12:50:37 PM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event PermissionCheckEvent(sender=ThSDTM, permission=bungeetablistplus.seevanished, hasPermission=false) to listener net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener@435871cb
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:544)
    at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:516)
    at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInWorld(PermissionsChecker.java:222)
    at net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener.onPermissionCheck(BungeeEventListener.java:131)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
    at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:463)
    at codecrafter47.bungeetablistplus.managers.PermissionManager.hasPermission(PermissionManager.java:357)
    at codecrafter47.bungeetablistplus.managers.PlayerManagerImpl.<init>(PlayerManagerImpl.java:48)
    at codecrafter47.bungeetablistplus.BungeeTabListPlus.constructPlayerManager(BungeeTabListPlus.java:562)
    at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:154)
    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:104)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    12:51:01 [SEVERE] Mar 04, 2016 12:51:01 PM net.md_5.bungee.event.EventBus post
  WARNING: Error dispatching event PermissionCheckEvent(sender=vaneagps, permissio
  n=bungeetablistplus.seevanished, hasPermission=false) to listener net.alpenblock
  .bungeeperms.platform.bungee.BungeeEventListener@435871cb
  java.lang.NullPointerException
      at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.
  java:544)
      at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.
  java:516)
      at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInW
  orld(PermissionsChecker.java:222)
      at net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener.onPermissi
  onCheck(BungeeEventListener.java:131)
      at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorI
  mpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:1
  9)
      at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
      at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374
  )
      at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:463)
      at codecrafter47.bungeetablistplus.managers.PermissionManager.hasPermission(
  PermissionManager.java:357)
      at codecrafter47.bungeetablistplus.managers.PlayerManagerImpl.<init>(PlayerM
  anagerImpl.java:48)
      at codecrafter47.bungeetablistplus.BungeeTabListPlus.constructPlayerManager(
  BungeeTabListPlus.java:562)
      at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:154
  )
      at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:104)
      at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java
  :1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.jav
  a:617)
      at java.lang.Thread.run(Thread.java:745)

**Comment by weaondara** [comment]
hi
it's required to set useuuid and backend to the same value
if you want to use mysql backends and mysql uuidplayerdb you need to configurate the mysql login data in every bp config on all servers
most likely you don't need regex permsissions
personally i recomment to use mysql2 as backend, useuuid true, uuidplayerdb mysql and regexperms false

**Comment by TheSDTM** [comment]
Ok, thank you. One more question: is it possible to set timer to user's group? Like in PermissionEx. I want to sell vip for 1 month, but I can find command that only gives permanent group

**Comment by phil568622** [comment]
Currently not possible out of the box. This feature may be included later on, but buycraft and mcmarket both have a feature to run a command after the rank has expired.
