### ISSUE TITLE
BaungeeTabListPlus

### ISSUE THREAD

**Issue by TheSDTM** [weaondara/BungeePerms#240]
I have this problem. BaungeeTabListPlus doesn't show prefixes
06:40:54 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException
06:40:54 [SEVERE] [BungeeTabListPlus] An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.
java.lang.NullPointerException

It is past from my config:

useUUIDs: true
useregexperms: false
grouppermission: true
backendtype: MySQL2
uuidplayerdb: MySQL
tablePrefix: bungeeperms_
uuidfetcher:
  cooldown: 3000
saveAllUsers: true
deleteUsersOnCleanup: false

**Comment by TheSDTM** [comment]
And i still get 
[09:57:14 WARN]: [BungeePerms] §4Misconfiguration: UUIDs on Bungeecord and Bukkit/Spigot differ. Check your Spigot/Bukkit and Bungeecord config!

But every config in my bengee network has the same settings (except server name)

**Comment by weaondara** [comment]
uuids on bungeecord and spigot do not match
you most likely forgot to enable bungeecord in one of your spigot.yml or bungeecord does not forward uuids properly

**Comment by weaondara** [comment]
reguarding the first error you posted it would help much more when you also post the stacktrace of the exception
if you cannot find one (e.g. it's not printed due to spam suppression) scroll up until you find one

**Comment by TheSDTM** [comment]
Yes, It wasn't enabled in spigot.yml. Thank you. But what about prefixes in BungeeTabListPlus?

**Comment by TheSDTM** [comment]
this one?
WARNING: Error dispatching event PermissionCheckEvent(sender=D1Warm, permission=bungeetablistplus.seevanished, hasPermission=false) to listener net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener@29a60c27
java.lang.NullPointerException
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:544)
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:516)
	at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInWorld(PermissionsChecker.java:222)
	at net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener.onPermissionCheck(BungeeEventListener.java:131)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:463)
	at codecrafter47.bungeetablistplus.managers.PermissionManager.hasPermission(PermissionManager.java:357)
	at codecrafter47.bungeetablistplus.managers.PlayerManagerImpl.<init>(PlayerManagerImpl.java:48)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.constructPlayerManager(BungeeTabListPlus.java:562)
	at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:154)
	at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:104)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


06:35:36 [SEVERE] Mar 07, 2016 6:35:36 AM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event PermissionCheckEvent(sender=sdf2323d, permission=bungeetablistplus.seevanished, hasPermission=false) to listener net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener@29a60c27
java.lang.NullPointerException
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:544)
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:516)
	at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInWorld(PermissionsChecker.java:222)
	at net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener.onPermissionCheck(BungeeEventListener.java:131)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:463)
	at codecrafter47.bungeetablistplus.managers.PermissionManager.hasPermission(PermissionManager.java:357)
	at codecrafter47.bungeetablistplus.managers.PlayerManagerImpl.<init>(PlayerManagerImpl.java:48)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.constructPlayerManager(BungeeTabListPlus.java:562)
	at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:154)
	at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:104)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


06:35:37 [SEVERE] Mar 07, 2016 6:35:37 AM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event PermissionCheckEvent(sender=D1Warm, permission=bungeetablistplus.seevanished, hasPermission=false) to listener net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener@29a60c27
java.lang.NullPointerException
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:544)
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:516)
	at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInWorld(PermissionsChecker.java:222)
	at net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener.onPermissionCheck(BungeeEventListener.java:131)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:463)
	at codecrafter47.bungeetablistplus.managers.PermissionManager.hasPermission(PermissionManager.java:357)
	at codecrafter47.bungeetablistplus.managers.PlayerManagerImpl.<init>(PlayerManagerImpl.java:48)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.constructPlayerManager(BungeeTabListPlus.java:562)
	at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:154)
	at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:104)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


06:35:37 [SEVERE] Mar 07, 2016 6:35:37 AM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event PermissionCheckEvent(sender=D1Warm, permission=bungeetablistplus.seevanished, hasPermission=false) to listener net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener@29a60c27
java.lang.NullPointerException
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:544)
	at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:516)
	at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOrConsoleOnServerInWorld(PermissionsChecker.java:222)
	at net.alpenblock.bungeeperms.platform.bungee.BungeeEventListener.onPermissionCheck(BungeeEventListener.java:131)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:463)
	at codecrafter47.bungeetablistplus.managers.PermissionManager.hasPermission(PermissionManager.java:357)
	at codecrafter47.bungeetablistplus.managers.PlayerManagerImpl.<init>(PlayerManagerImpl.java:48)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.constructPlayerManager(BungeeTabListPlus.java:562)
	at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:154)
	at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:104)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by TheSDTM** [comment]
It repeats nearly 200 times

**Comment by weaondara** [comment]
did bp connect to mysql properly at startup?

**Comment by TheSDTM** [comment]
Yes, absolutely, because I execute command like set group on bungeecord, not on servers

**Comment by TheSDTM** [comment]
And no error show

**Comment by weaondara** [comment]
try '/bp user D1Warm info' and post the output

**Comment by TheSDTM** [comment]
>bp user D1Warm info
14:48:23 [INFO] About D1Warm
14:48:23 [INFO] UUID: 4cbe8294-571d-3996-8e9f-8d72eb6f1bcd
14:48:23 [INFO] Groups: default (118)
14:48:23 [INFO] User permissions: 0
14:48:23 [INFO] All permissions: 118
14:48:23 [INFO] Display: (none)
14:48:23 [INFO] Prefix: (none)
14:48:23 [INFO] Suffix: (none)
14:48:23 [INFO] Full prefix: P 
14:48:23 [INFO] Full suffix:

**Comment by weaondara** [comment]
ah the fix i told you should fix this too ... because uuid where overridden with wrong ones and the bp could not find the usernames and threw an error

**Comment by weaondara** [comment]
if the problem persists from now on let me know

**Comment by TheSDTM** [comment]
OK, thank you!
