### ISSUE TITLE
NullPointerException using api

### ISSUE THREAD

**Issue by WoutDev** [weaondara/BungeePerms#245]
Getting exception:
```
15:59:49 [WARNING] Error in dispatching command
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.
java:613)
    at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.
java:591)
    at staffchat.commands.StaffChat.execute(StaffChat.java:80)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.ja
va:162)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.ja
va:116)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:116)

    at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessa
geDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDeco
der.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDeco
der.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessa
geDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:319)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandle
r.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstract
ChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractCh
annelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPip
eline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNi
oByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:51
1)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLo
op.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:3
82)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEven
tExecutor.java:116)
    at java.lang.Thread.run(Unknown Source)
```

Code executed:
`
BungeePerms.getInstance().getPermissionsManager().getMainGroup(BungeePerms.getInstance().getPermissionsManager().getUser(pp.getUniqueId())).getName()));
`

pp is a valid ProxiedPlayer object.

Error points out to [this](https://github.com/weaondara/BungeePerms/blob/master/src/main/java/net/alpenblock/bungeeperms/PermissionsManager.java#L613) line of code.

I'm using the latest BungeePerms version freshly downloaded from the official spigotmc resource page.

Bungeecord version:
`16:12:14 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT
:"bd07be8":1079`

**Comment by weaondara** [comment]
most likely bungeeperms in cnfigured not to use uuids

**Comment by WoutDev** [comment]
You are indeed correct.
