### ISSUE TITLE
Beim Gruppen setzen. 

### ISSUE THREAD

**Issue by koenigheine** [weaondara/BungeePerms#249]
java.lang.NullPointerException
        at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:540) ~[?:?]
        at net.alpenblock.bungeeperms.PermissionsManager.getUser(PermissionsManager.java:512) ~[?:?]
        at net.alpenblock.bungeeperms.platform.bukkit.BPPermissible.recalculatePermissions(BPPermissible.java:146) ~[?:?]
        at net.alpenblock.bungeeperms.platform.bukkit.BPPermissible.<init>(BPPermissible.java:102) ~[?:?]
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitEventListener.enable(BukkitEventListener.java:58) ~[?:?]
        at net.alpenblock.bungeeperms.BungeePerms.enable(BungeePerms.java:83) ~[?:?]
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:88) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:740) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_server.jar:git-Spigot-db6de12-efe04b8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_server.jar:git-Spigot-db6de12-efe04b8]

---

[21:08:36 WARN]: Exception in thread "Craft Scheduler Thread - 15"
[21:08:36 WARN]: org.apache.commons.lang.UnhandledException: Plugin BungeePerms v3.0 dev #47 generated an exception while executing task 66
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitNotifier.sendConfig(BukkitNotifier.java:196)
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitNotifier.sendPM(BukkitNotifier.java:150)
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitNotifier.reloadUser(BukkitNotifier.java:60)
        at net.alpenblock.bungeeperms.PermissionsManager.removeUserGroup(PermissionsManager.java:867)
        at net.alpenblock.bungeeperms.CommandHandler.handleUserCommandsGroupSet(CommandHandler.java:816)
        at net.alpenblock.bungeeperms.CommandHandler.handleUserCommands(CommandHandler.java:276)
        at net.alpenblock.bungeeperms.CommandHandler.onCommand(CommandHandler.java:63)
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin.onCommand(BukkitPlugin.java:104)
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin$1$1.run(BukkitPlugin.java:140)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Dominikzocker141** [comment]
du bist wahrscheinlich vom mysql server geworfen geworden,
ist mir auch schon passiert

**Comment by weaondara** [comment]
most likely the mysql settings or the uuid settings in the config are wrong
