### ISSUE TITLE
MySQL bug

### ISSUE THREAD

**Issue by Schmiddinger** [weaondara/BungeePerms#326]
Dear community & BP Team,
I have installed BungeePerms on my network and set it up with mysql. It connects to my server and it had created the database, but when I start the server, this error comes:

`[18:47:30 INFO]: [BungeePerms] Loading BungeePerms v3.0 dev #47
[18:47:31 INFO]: [BungeePerms] loading permissions ...
[18:47:31 WARN]: java.lang.RuntimeException: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'server.bperms_permissions2.id' which is not in SELECT list; this is incompatible with DISTINCT
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:232)
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:98)
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.io.mysql2.MysqlPermsAdapter2.getGroups(MysqlPermsAdapter2.java:44)
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.io.MySQL2BackEnd.loadGroups(MySQL2BackEnd.java:68)
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.PermissionsManager.loadPerms(PermissionsManager.java:116)
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:65)
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin.onLoad(BukkitPlugin.java:73)
[18:47:31 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[18:47:31 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[18:47:31 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[18:47:31 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:47:31 WARN]: Caused by: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'server.bperms_permissions2.id' which is not in SELECT list; this is incompatible with DISTINCT
[18:47:31 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[18:47:31 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[18:47:31 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[18:47:31 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[18:47:31 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[18:47:31 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[18:47:31 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
[18:47:31 WARN]:        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474)
[18:47:31 WARN]:        at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:218)
[18:47:31 WARN]:        ... 11 more
[18:47:31 INFO]: [BungeePerms] permissions loaded`
And so, it doesn't load the groups and the players.
Thanks in advance,
Schmiddinger

**Comment by 2called-chaos** [comment]
If you have control over the MySQL server you can apply this change to your server globally or you have to fiddle it into the code as I did with ckSurf:

https://github.com/nikooo777/ckSurf/pull/58

**Comment by Schmiddinger** [comment]
I have control over the mysql server, but I'm not so good in mysql server managment. What do you mean with "you can apply this change to your server globally"?

Thanks

**Comment by Schmiddinger** [comment]
Oh, i found it.
Thanks
