### ISSUE TITLE
unable to start.

### ISSUE THREAD

**Issue by darkt1981** [weaondara/BungeePerms#373]
**Describe the bug**
Unable to load jar file.

**To Reproduce**
just by starting the server is does this plugin support open-jdk 11 ?

**Expected behavior**

**Screenshots or log**

[21:34:05] [Server thread/WARN]: Legacy plugin BungeePerms v4.0 dev #106 does not specify an api-version.
[21:34:05] [Server thread/ERROR]: Could not load 'plugins/BungeePerms-4.0-dev-106.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Method <clinit> is not static in class file net/alpenblock/bungeeperms/platform/bukkit/BukkitPlugin
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) [Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassFormatError: Method <clinit> is not static in class file net/alpenblock/bungeeperms/platform/bukkit/BukkitPlugin
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:398) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot_Latest_1.15.2.jar:git-Spigot-2f5d615-d07a78b]
... 6 more

**Additional context**
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode)

**Comment by darkt1981** [comment]
found the issue xD couldnt connect to mysql db
