### ISSUE TITLE
use MSSQL as database for this plugin

### ISSUE THREAD

**Issue by Venkinovec** [weaondara/BungeePerms#384]
**Is your feature request related to a problem? Please describe.**
We are already using MSSQL with many MC servers, but as it seems your plugins does not have drivers to communicate.
`java.sql.SQLException: No suitable driver found for jdbc:sqlserver://localhost:1433;databaseName=Bungeecord;`

If i'm wrong, could you please explain me what is needed ?
Thank you

**Comment by aurorasmiles** [comment]
Seems like your config is faulty. Check out our wiki for how to configure the url correctly. It seems like you replaced parts of the url without knowing what they do. All you have to do is replace localhost with the address where your database is, if different, replace 3306 with the port, if different, and replace the part behind the address:port/HERE with your database name. Don't replace or remove anything else.

**Comment by Venkinovec** [comment]
Update, I used the syntax as described in wiki. Still won't connect but also crashes Bungeecord.
`[BungeePerms] Connecting to database
15:03:33 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4f6ee6e4, id=0, owner=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin@1ab3a8c8, task=net.alpenblock.bungeeperms.metrics.bungee.Metrics$$Lambda$3/1438098656@4466af20, delay=120000, period=1800000, running=true) encountered an exception
java.lang.NullPointerException
    at net.alpenblock.bungeeperms.metrics.bungee.Metrics.getServerData(Metrics.java:196)
    at net.alpenblock.bungeeperms.metrics.bungee.Metrics.submitData(Metrics.java:227)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)`
Config:
 `mysql:
  user: bungeecord
  password: <password>
  tableprefix: bungeeperms_
  url: jdbc:mysql://localhost:1433/Bungeecord?autoReconnect=true&dontTrackOpenResources=true`

My sql is cofigured correctly as I tested with managment studio to connect
![image](https://user-images.githubusercontent.com/25304952/110332007-18e67f80-8020-11eb-86b8-dcfc77a2c9a2.png)
![image](https://user-images.githubusercontent.com/25304952/110332029-213eba80-8020-11eb-8dc5-48aa85e8a2b3.png)

**Comment by aurorasmiles** [comment]
Please paste the complete exception to a paste site

**Comment by Venkinovec** [comment]
https://pastebin.com/V8KTxBh4

**Comment by Venkinovec** [comment]
Have you found out something ?

> https://pastebin.com/V8KTxBh4

**Comment by aurorasmiles** [comment]
Oh wait, you are using MSSQL not MySQL?
I'm sorry, my mistake then. I'll have to look into using that then, I'm not sure if it is supported atm

**Comment by Venkinovec** [comment]
OK, let me know if you find anything.

**Comment by Venkinovec** [comment]
Hello, I was investigating the jdbc driver ( `jdbc:mysql://localhost:1433/.....`) a according to microsoft it should be working with MSSQL without any problem. That is if it really is jdbc.
