### ISSUE TITLE
can‘t work witch  Velocity 3.0.0

### ISSUE THREAD

**Issue by KnightBlood** [weaondara/BungeePerms#390]
[22:47:56 ERROR]: Can't create plugin bungeeperms
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchMethodError: 'void CommandManager.register(Command, String[])'
  at VelocityPlugin.<init>(VelocityPlugin.java:94)
  at VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating VelocityPlugin

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Command:              "com.velocitypowered.api.command.Command"
CommandManager:       "com.velocitypowered.api.command.CommandManager"
VelocityPlugin:       "net.alpenblock.bungeeperms.platform.velocity.VelocityPlugin"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[velocity-3.0.0.jar:3.0.0]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[velocity-3.0.0.jar:3.0.0]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:152) ~[velocity-3.0.0.jar:3.0.0]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:325) ~[velocity-3.0.0.jar:3.0.0]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:223) ~[velocity-3.0.0.jar:3.0.0]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity-3.0.0.jar:3.0.0]
Caused by: java.lang.NoSuchMethodError: 'void com.velocitypowered.api.command.CommandManager.register(com.velocitypowered.api.command.Command, java.lang.String[])'
        at net.alpenblock.bungeeperms.platform.velocity.VelocityPlugin.loadcmds(VelocityPlugin.java:167) ~[?:?]
        at net.alpenblock.bungeeperms.platform.velocity.VelocityPlugin.<init>(VelocityPlugin.java:112) ~[?:?]
        at net.alpenblock.bungeeperms.platform.velocity.VelocityPlugin$$FastClassByGuice$$266522.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.alpenblock.bungeeperms.platform.velocity.VelocityPlugin$$FastClassByGuice$$266522.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.0.0.jar:3.0.0]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity-3.0.0.jar:3.0.0]
        ... 6 more

**Comment by aurorasmiles** [comment]
should be fixed in build 134 b14e36d2d4ba97a9c2b2be1e1ac58002fdebb034
