### ISSUE TITLE
Error on Paper Server

### ISSUE THREAD

**Issue by Lice2** [weaondara/BungeePerms#392]
**Describe the bug**
Error in the console : paper-1.17.1-133 : java 16

**To Reproduce**
This error occurs when players log in from one server to the other 
Java 16 
**Expected behavior**

**Screenshots or log**
[00:01:22] [User Authenticator #1/INFO]: [BungeePerms] Login von xxxxx (74938985-c1fa-3d16-a788-16cf8a2c30f9)
[00:01:22] [User Authenticator #1/INFO]: UUID of player xxxxxxx is 74938985-c1fa-3d16-a788-16cf8a2c30f9
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: Exception in thread "ForkJoinPool.commonPool-worker-5" java.util.ConcurrentModificationException
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:335)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.LinkedHashSet.<init>(LinkedHashSet.java:170)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.platform.bukkit.BPPermissible.getEffectiveSuperPerms(BPPermissible.java:281)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.platform.bukkit.SuperPermsPreProcessor.getSuperPerms(SuperPermsPreProcessor.java:54)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.platform.bukkit.SuperPermsPreProcessor.process(SuperPermsPreProcessor.java:72)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.PermissionsResolver.preprocess(PermissionsResolver.java:56)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.User.hasPerm(User.java:217)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.User.hasPerm(User.java:192)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.PermissionsChecker.hasPermOnServerInWorld(PermissionsChecker.java:93)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.platform.bukkit.bridge.bridges.worldedit.BungeePermsResolver.hasPermission(BungeePermsResolver.java:70)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.alpenblock.bungeeperms.platform.bukkit.bridge.bridges.worldedit.BungeePermsResolver.hasPermission(BungeePermsResolver.java:82)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.sk89q.wepif.PermissionsResolverManager.hasPermission(PermissionsResolverManager.java:170)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:174)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.sk89q.worldedit.command.util.PermissionCondition.lambda$satisfied$0(PermissionCondition.java:47)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.Optional.map(Optional.java:260)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.sk89q.worldedit.command.util.PermissionCondition.satisfied(PermissionCondition.java:47)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitCommandInspector.testPermission(BukkitCommandInspector.java:81)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.sk89q.bukkit.util.DynamicPluginCommand.testPermissionSilent(DynamicPluginCommand.java:100)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:48)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:20)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:400)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.minecraft.commands.CommandDispatcher.sendAsync(CommandDispatcher.java:364)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at net.minecraft.commands.CommandDispatcher.lambda$sendCommands$4(CommandDispatcher.java:347)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[00:01:24] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Additional context**

**Comment by aurorasmiles** [comment]
Fixed in 205a99620c04c6bd3bccc7876d487ed3be0aa21b
