### ISSUE TITLE
BungeePerms.getInstance() is null

### ISSUE THREAD

**Issue by ech0Schokolade** [weaondara/BungeePerms#403]
I have searched the whole internet and haven't found this bug. If it even is one and I'm not just being stupid.
I want to create a BungeeCord Plugin using (ofc the BungeeCord API and) the BungeePerms API. Now this is the first time of me using BungeePerms and when I try to load the plugin. It shows this error: "java.lang.NullPointerException: Cannot invoke "net.alpenblock.bungeeperms.BungeePerms.load()" because the return value of "net.alpenblock.bungeeperms.BungeePerms.getInstance()" is null"

Reproducing is simple: Make a new BungeeCord/BungeePerms plugin and the only thing you need to do is put "BungeePerms.getInstance().enable();" into the onEnable()

java.lang.NullPointerException: Cannot invoke "net.alpenblock.bungeeperms.BungeePerms.load()" because the return value of "net.alpenblock.bungeeperms.BungeePerms.getInstance()" is null
    at de.ech0schokolade.permissionsystem.Main.onEnable(Main.java:12)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at eu.cloudnetservice.wrapper.Wrapper.lambda$startApplication$2(Wrapper.java:260)
    at java.base/java.lang.Thread.run(Thread.java:840)

I've tried to use "BungeePerms.getInstance().load();" aswell as just "enable()" and both. Do I need to set the instance anywhere? (I feel so dumb not knowing what to do here lol)

**Comment by aurorasmiles** [comment]
You don't need to load or enable anything. You need to make sure your plugin has BungeePerms as a dependency, have BungeePerms installed, and then you should be able to just get a BungeePerms instance with `BungeePerms.getInstance()`

**Comment by ech0Schokolade** [comment]
The dependency Version and the Plugin Version has to be the same, right?

**Comment by aurorasmiles** [comment]
Ideally

**Comment by ech0Schokolade** [comment]
So, I've got both with the same Version (4.0-dev-143), but when I then e.g. execute a command, it still says that the instance is null:

java.lang.NullPointerException: Cannot invoke "net.alpenblock.bungeeperms.BungeePerms.getPermissionsManager()" because the return value of "net.alpenblock.bungeeperms.BungeePerms.getInstance()" is null


The dependency:
    <dependency>
      <groupId>net.alpenblock</groupId>
      <artifactId>BungeePerms</artifactId>
      <version>4.0-dev-143</version>
    </dependency>

**Comment by aurorasmiles** [comment]
Without knowing anything I can't really help you. And GitHub issues aren't really the right place for programming support.
