### ISSUE TITLE
Error dispatching event

### ISSUE THREAD

**Issue by dzmen** [weaondara/BungeePerms#52]
Hello weaondara,

I dont know if I do something wrong but I get this error every time someone join's the server:

WARNING: Error dispatching event PermissionCheckEvent(sender=dzmen, permission=bungeefilter.bypass, hasPermission=false) to listener net.alpenblock.bungeeperms.PermissionsManager@59c9deac
java.lang.NullPointerException
	at net.alpenblock.bungeeperms.PermissionsManager.hasPermOrConsoleOnServerInWorld(PermissionsManager.java:840)
	at net.alpenblock.bungeeperms.PermissionsManager.onPermissionCheck(PermissionsManager.java:548)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:353)
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:388)
	at com.minecraftdimensions.bungeechatfilter.PlayerChatListener.playerChat(PlayerChatListener.java:17)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:353)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:92)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:155)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:155)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:116)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:494)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:461)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:724)

Could you maybe help me with a solution?

**Comment by weaondara** [comment]
2.4

**Comment by Kalorte** [comment]
Same problem in 2.4 for me :/

**Comment by dzmen** [comment]
My problem is gone in 2.4 :). Thanks!

**Comment by weaondara** [comment]
any news on this? if so please paste the stacktraces
otherwise this ticket will be closed
