### ISSUE TITLE
Paar Probleme 

### ISSUE THREAD

**Issue by Nosxxx** [weaondara/BungeePerms#62]
Hallo,
wenn man eine neuere BungeeVersion nutzt kommt folgender Fehler (Warnung)

```
15.07.2014 08:22 [WARNUNG] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
	at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
	at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:391)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:461)
	at net.alpenblock.bungeeperms.BungeePerms$1.execute(BungeePerms.java:1877)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:149)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:106)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:95)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
15.07.2014 08:22 [WARNUNG] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
	at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
	at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:391)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:461)
	at net.alpenblock.bungeeperms.BungeePerms$1.execute(BungeePerms.java:1877)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:149)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:106)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:95)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
```

Außerdem tritt bei einem Befehl immer folgendes auf:

```
15.07.2014 08:16 [SCHWERWIEGEND] java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
15.07.2014 08:16 [SCHWERWIEGEND] 	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
15.07.2014 08:16 [SCHWERWIEGEND] 	at java.util.ArrayList.get(ArrayList.java:411)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.PermissionsResolver.hasNormal(PermissionsResolver.java:48)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.PermissionsResolver.has(PermissionsResolver.java:21)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.User.hasPermOnServer(User.java:55)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.PermissionsManager.hasPermOrConsoleOnServerInWorld(PermissionsManager.java:954)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.PermissionsManager.onPermissionCheck(PermissionsManager.java:662)
15.07.2014 08:16 [SCHWERWIEGEND] 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
15.07.2014 08:16 [SCHWERWIEGEND] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15.07.2014 08:16 [SCHWERWIEGEND] 	at java.lang.reflect.Method.invoke(Method.java:606)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:354)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:389)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:138)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:106)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:95)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
15.07.2014 08:16 [SCHWERWIEGEND] 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
15.07.2014 08:16 [SCHWERWIEGEND] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
15.07.2014 08:16 [SCHWERWIEGEND] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by weaondara** [comment]
done
