### ISSUE TITLE
An internal error occured! (since BungeePerms)

### ISSUE THREAD

**Issue by re4ly** [weaondara/BungeePerms#68]
An internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
java.lang.NullPointerException: player is null
    at net.alpenblock.bungeeperms.PermissionsManager.getMainGroup(PermissionsManager.java:288)
    at codecrafter47.bungeetablistplus.managers.PermissionManager.getMainGroup(PermissionManager.java:42)
    at codecrafter47.bungeetablistplus.managers.PlayerManager.getPlayers(PlayerManager.java:62)
    at codecrafter47.bungeetablistplus.section.FillPlayersSection.precalculate(FillPlayersSection.java:65)
    at codecrafter47.bungeetablistplus.config.TabListProvider.getTabList(TabListProvider.java:133)
    at codecrafter47.bungeetablistplus.tablisthandler.TabList17.recreate(TabList17.java:82)
    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:63)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by weaondara** [comment]
o.O ... seem to be an bungeetablistplus issue
