### ISSUE TITLE
AccesControlExeption bei Commands

### ISSUE THREAD

**Issue by 4ch3los** [weaondara/BungeePerms#72]
Wenn ich den einen bp comamnd ausführe kommt eine AccesControlExeption
>bp
00:16:41 [WARNUNG] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group access
    at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)
    at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)
    at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
    at java.lang.Thread.init(Thread.java:391)
    at java.lang.Thread.init(Thread.java:349)
    at java.lang.Thread.<init>(Thread.java:461)
    at net.alpenblock.bungeeperms.BungeePerms$1.execute(BungeePerms.java:1877)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:162)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:57)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
00:16:41 [INFORMATION] Welcome to BungeePerms, a BungeeCord permissions plugin

LG 4ch3los

**Comment by nette18** [comment]
I have this error too

**Comment by 4ch3los** [comment]
fixed it for me! you can download my fixed version here http://root1.4ch3los.de/BungeePerms-2.3.0.jar

**Comment by weaondara** [comment]
fixed in 2.4
